### ISSUE TITLE
Grunt build failed

### ISSUE THREAD

**Issue by driccio** [flowhub/the-graph#240] opened 2016-01-21 09:51 UTC
Hi,

Here the error when running "grunt build" :
Running "browserify:libs" (browserify) task
`>> Error: Cannot find module './parser' from '/private/tmp/the-graph/node_modules/noflo/node_modules/babel-core/node_modules/babylon'
Warning: Error running grunt-browserify. Use --force to continue.`

**Comment by driccio** [comment] 2016-01-21 10:46
I fix that quickly by using "noflo": "0.5.14" dep in package.json

**Comment by alhafoudh** [comment] 2016-01-26 16:13
@driccio that did not help for me, what else did you do?

+1

**Comment by kinimodmeyer** [comment] 2016-01-28 22:03
i think this bug is important, you can not install it anymore :(
who can fix it?

**Comment by driccio** [comment] 2016-02-02 07:00
@alhafoudh As I said, I only changed the version "^0.5.21" of noflo by version "0.5.14" (without the '^' prefix) in package.json. Then relaunch npm install and grunt build. Nothing else.

**Comment by lacek** [comment] 2016-02-22 07:21
I am using Mac and had python 3 which triggered the following error:

```
...
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.5.1, which is not supported by gyp.
```

which could be solved by running with the python option `npm install --python=/usr/bin/python2.7`.

And then I got another error due to node 5.6:

```
...

  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../../nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                         \
...
```

which could be solved by downgrading node to version 4: `brew install homebrew/versions/node4-lts`.

**Comment by jonnor** [comment] 2016-02-22 10:31
@lacek which version of of nodejs did you have before when it failed?

**Comment by lacek** [comment] 2016-02-22 10:32
I had failed with 5.3 (or 5.6, can't be sure which one).

**Comment by jonnor** [comment] 2016-12-20 15:34
We're building successfully on Node.js 7 now on Travis CI. Closing issue, please reopen with information to reproduce if issues persist.

**Closed by jonnor** 2016-12-20 15:34 UTC
