### ISSUE TITLE
canvas-prebuilt dependency is no more

### ISSUE THREAD

**Issue by WilliamRClark** [flowhub/the-graph#392] opened 2020-11-18 17:42 UTC
One of the project dependencies is no longer available which breaks the build:

> canvas-prebuilt@1.6.11 install C:\git\EncantoPOC\wrc-the-graph\node_modules\canvas-prebuilt
> node-pre-gyp install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\git\EncantoPOC\wrc-the-graph\node_modules\node-pre-gyp\lib\install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:327:22)
node-pre-gyp ERR! stack     at Request.onRequestResponse (C:\git\EncantoPOC\wrc-the-graph\node_modules\request\request.js:1059:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:315:20)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:469:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:295:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:271:9)
node-pre-gyp ERR! System Windows_NT 10.0.19041
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\git\\EncantoPOC\\wrc-the-graph\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" 
"install"
node-pre-gyp ERR! cwd C:\git\EncantoPOC\wrc-the-graph\node_modules\canvas-prebuilt
node-pre-gyp ERR! node -v v12.18.3
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-win32-x64.tar.gz

**Comment by WilliamRClark** [comment] 2020-11-18 17:49
This can't be changed to noflo-canvas without code changes in several places because they aren't compatible.

**Comment by bergie** [comment] 2020-11-18 18:06
Dupe of #391

**Closed** 2020-11-19 08:26 UTC
